export type Status = 'ACTIVE' | 'DISABLED' | 'INVITED';
export type ScopeType = 'PLATFORM' | 'COMPANY' | 'COMMUNITY';

export type UserRecord = {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
  passwordHash: string;
  status: Status;
  lastLoginAt: Date | null;
  disabledAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type CompanyRecord = { id: string; code: string; name: string; status: Status; disabledAt: Date | null; createdAt: Date; updatedAt: Date };
export type CommunityRecord = { id: string; propertyCompanyId: string; code: string; name: string; address: string | null; status: Status; disabledAt: Date | null; createdAt: Date; updatedAt: Date };
export type MembershipRecord = { id: string; userId: string; propertyCompanyId: string; membershipType: 'PROPERTY_EMPLOYEE' | 'PROPERTY_ADMIN'; status: Status; joinedAt: Date; leftAt: Date | null; createdAt: Date; updatedAt: Date };
export type EmployeeRecord = { id: string; companyMembershipId: string; employeeNo: string; department: string | null; position: string | null; employeeType: string | null; joinedAt: Date; leftAt: Date | null; createdAt: Date; updatedAt: Date };
export type RoleRecord = { id: string; code: string; name: string; scopeType: ScopeType; createdAt: Date; updatedAt: Date };
export type PermissionRecord = { id: string; code: string; name: string; resource: string; action: string; createdAt: Date; updatedAt: Date };
export type AssignmentRecord = { id: string; userId: string; roleId: string; propertyCompanyId: string | null; communityId: string | null; createdAt: Date; revokedAt: Date | null };
export type SessionRecord = { id: string; userId: string; tokenHash: string; activePropertyCompanyId: string | null; expiresAt: Date; lastSeenAt: Date; revokedAt: Date | null; userAgent: string | null; ipHash: string | null; createdAt: Date };
export type BuildingRecord = { id: string; communityId: string; code: string; name: string; displayName: string | null; legacyCode: string | null; status: 'ACTIVE' | 'INACTIVE'; disabledAt: Date | null; createdAt: Date; updatedAt: Date };
export type BuildingUnitRecord = { id: string; buildingId: string; code: string; name: string; displayName: string | null; status: 'ACTIVE' | 'INACTIVE'; disabledAt: Date | null; createdAt: Date; updatedAt: Date };
export type HouseRecord = { id: string; buildingId: string; buildingUnitId: string | null; code: string; floor: number | null; buildingArea: string | null; usableArea: string | null; displayName: string | null; legacyCode: string | null; status: 'ACTIVE' | 'RENOVATING' | 'INACTIVE'; disabledAt: Date | null; createdAt: Date; updatedAt: Date; communityId?: string; propertyCompanyId?: string };
export type PersonRecord = { id: string; propertyCompanyId: string; userId: string | null; name: string; phone: string | null; gender: 'MALE' | 'FEMALE' | 'OTHER' | 'UNKNOWN' | null; status: 'ACTIVE' | 'DISABLED'; disabledAt: Date | null; createdAt: Date; updatedAt: Date };
export type HouseRelationshipRecord = { id: string; houseId: string; personId: string; relationshipType: 'OWNER' | 'TENANT' | 'FAMILY_MEMBER' | 'OCCUPANT'; ownershipShare: string | null; isPrimaryContact: boolean; startDate: string; endDate: string | null; verificationStatus: 'UNVERIFIED' | 'PENDING' | 'VERIFIED' | 'REJECTED'; reviewedAt: Date | null; reviewedByUserId: string | null; verificationNote: string | null; createdAt: Date; updatedAt: Date };
export type BuildingDto = BuildingRecord & { displayAddress: string };
export type BuildingUnitDto = BuildingUnitRecord;
export type HouseDto = HouseRecord & { displayCode: string; displayAddress: string };
export type PersonDto = Omit<PersonRecord, 'phone'> & { maskedPhone: string | null };
export type PersonContactDto = Pick<PersonRecord, 'id' | 'name' | 'phone'>;
export type PaginatedResult<T> = { items: T[]; page: number; pageSize: number; total: number };
export type RelationshipFilters = { includeHistory?: boolean; houseId?: string; personId?: string };
export type PropertyFilters = { page?: number; pageSize?: number; communityId?: string; buildingId?: string; unitId?: string; houseId?: string; keyword?: string; relationshipType?: HouseRelationshipRecord['relationshipType']; status?: string };

export type Scope = {
  userId: string;
  platform: boolean;
  companyWide: boolean;
  companyIds: string[];
  communityIds: string[];
  roles: string[];
  permissions: string[];
  activePropertyCompanyId: string | null;
};

export type AuditInput = {
  propertyCompanyId?: string | null;
  communityId?: string | null;
  actorUserId?: string | null;
  action: string;
  resourceType?: string;
  resourceId?: string;
  requestId?: string;
  beforeData?: unknown;
  afterData?: unknown;
  ipHash?: string | null;
  userAgent?: string | null;
};

export interface Repository {
  findUserByPhone(phone: string): Promise<UserRecord | null>;
  findUserById(id: string): Promise<UserRecord | null>;
  hasCompanyMembership(userId: string, propertyCompanyId: string): Promise<boolean>;
  getCommunityCompanyId(communityId: string): Promise<string | null>;
  updateUserLastLogin(id: string): Promise<void>;
  createSession(input: Omit<SessionRecord, 'createdAt' | 'lastSeenAt' | 'revokedAt'>): Promise<SessionRecord>;
  findActiveSession(tokenHash: string): Promise<SessionRecord | null>;
  touchSession(id: string): Promise<void>;
  revokeSession(id: string): Promise<void>;
  listSessions(userId: string): Promise<SessionRecord[]>;
  scopeForUser(userId: string, activeCompanyId?: string | null): Promise<Scope>;
  listCompanies(scope: Scope): Promise<CompanyRecord[]>;
  getCompany(id: string, scope: Scope): Promise<CompanyRecord | null>;
  createCompany(input: { code: string; name: string }): Promise<CompanyRecord>;
  listCommunities(scope: Scope): Promise<CommunityRecord[]>;
  getCommunity(id: string, scope: Scope): Promise<CommunityRecord | null>;
  createCommunity(input: { propertyCompanyId: string; code: string; name: string; address?: string | null }): Promise<CommunityRecord>;
  updateCommunity(id: string, input: { name?: string; address?: string | null }, scope: Scope): Promise<CommunityRecord | null>;
  disableCommunity(id: string, scope: Scope): Promise<CommunityRecord | null>;
  listEmployees(scope: Scope): Promise<Array<EmployeeRecord & { user: UserRecord; membership: MembershipRecord }>>;
  getEmployee(id: string, scope: Scope): Promise<(EmployeeRecord & { user: UserRecord; membership: MembershipRecord }) | null>;
  createEmployee(input: { companyId: string; user: Omit<UserRecord, 'id' | 'createdAt' | 'updatedAt' | 'lastLoginAt' | 'disabledAt'>; employee: Omit<EmployeeRecord, 'id' | 'companyMembershipId' | 'createdAt' | 'updatedAt' | 'joinedAt' | 'leftAt'> }): Promise<{ user: UserRecord; membership: MembershipRecord; employee: EmployeeRecord }>;
  updateEmployee(id: string, input: { name?: string; phone?: string | null; status?: Status; department?: string | null; position?: string | null; employeeType?: string | null }, scope: Scope): Promise<(EmployeeRecord & { user: UserRecord; membership: MembershipRecord }) | null>;
  disableEmployee(id: string, scope: Scope): Promise<(EmployeeRecord & { user: UserRecord; membership: MembershipRecord }) | null>;
  listRoles(): Promise<RoleRecord[]>;
  listPermissions(): Promise<PermissionRecord[]>;
  assignRole(input: { userId: string; roleId: string; propertyCompanyId?: string | null; communityId?: string | null }): Promise<AssignmentRecord>;
  getAssignment(id: string): Promise<(AssignmentRecord & { role: RoleRecord }) | null>;
  revokeRole(id: string): Promise<void>;
  listAssignments(userId: string): Promise<Array<AssignmentRecord & { role: RoleRecord }>>;
  audit(input: AuditInput): Promise<void>;
  listBuildings(scope: Scope, filters?: PropertyFilters): Promise<BuildingDto[]>;
  getBuilding(id: string, scope: Scope): Promise<BuildingDto | null>;
  createBuilding(input: { communityId: string; code: string; name: string; displayName?: string | null; legacyCode?: string | null }): Promise<BuildingRecord>;
  updateBuilding(id: string, input: Partial<Pick<BuildingRecord, 'code' | 'name' | 'displayName' | 'legacyCode'>>, scope: Scope): Promise<BuildingRecord | null>;
  disableBuilding(id: string, scope: Scope): Promise<BuildingRecord | null>;
  listBuildingUnits(buildingId: string, scope: Scope): Promise<BuildingUnitDto[]>;
  getBuildingUnit(id: string, scope: Scope): Promise<BuildingUnitDto | null>;
  createBuildingUnit(input: { buildingId: string; code: string; name: string; displayName?: string | null }): Promise<BuildingUnitRecord>;
  updateBuildingUnit(id: string, input: Partial<Pick<BuildingUnitRecord, 'code' | 'name' | 'displayName'>>, scope: Scope): Promise<BuildingUnitRecord | null>;
  disableBuildingUnit(id: string, scope: Scope): Promise<BuildingUnitRecord | null>;
  listHouses(scope: Scope, filters?: PropertyFilters): Promise<PaginatedResult<HouseDto>>;
  getHouse(id: string, scope: Scope): Promise<HouseDto | null>;
  createHouse(input: { buildingId: string; buildingUnitId?: string | null; code: string; floor?: number | null; buildingArea?: string | null; usableArea?: string | null; displayName?: string | null; legacyCode?: string | null }): Promise<HouseRecord>;
  updateHouse(id: string, input: Partial<Pick<HouseRecord, 'buildingUnitId' | 'code' | 'floor' | 'buildingArea' | 'usableArea' | 'displayName' | 'legacyCode' | 'status'>>, scope: Scope): Promise<HouseRecord | null>;
  disableHouse(id: string, scope: Scope): Promise<HouseRecord | null>;
  listPeople(scope: Scope, filters?: PropertyFilters): Promise<PaginatedResult<PersonDto>>;
  getPerson(id: string, scope: Scope, options?: { includeHistory?: boolean }): Promise<PersonDto | null>;
  createPerson(input: { propertyCompanyId: string; userId?: string | null; name: string; phone?: string | null; gender?: PersonRecord['gender'] }): Promise<PersonRecord>;
  updatePerson(id: string, input: Partial<Pick<PersonRecord, 'name' | 'userId' | 'phone' | 'gender'>>, scope: Scope): Promise<PersonRecord | null>;
  disablePerson(id: string, scope: Scope): Promise<PersonRecord | null>;
  getPersonContact(id: string, scope: Scope): Promise<PersonContactDto | null>;
  listHouseRelationships(houseId: string, scope: Scope, includeHistory?: boolean): Promise<Array<HouseRelationshipRecord & { person: PersonDto }>>;
  listPersonRelationships(personId: string, scope: Scope, includeHistory?: boolean): Promise<Array<HouseRelationshipRecord & { house: HouseDto }>>;
  createHouseRelationship(input: { houseId: string; personId: string; relationshipType: HouseRelationshipRecord['relationshipType']; ownershipShare?: string | null; isPrimaryContact?: boolean; startDate: string; endDate?: string | null }): Promise<HouseRelationshipRecord>;
  updateHouseRelationship(id: string, input: Partial<Pick<HouseRelationshipRecord, 'relationshipType' | 'ownershipShare' | 'isPrimaryContact' | 'startDate' | 'endDate'>>, scope: Scope): Promise<HouseRelationshipRecord | null>;
  endHouseRelationship(id: string, endDate: string, scope: Scope): Promise<HouseRelationshipRecord | null>;
  verifyHouseRelationship(id: string, status: 'VERIFIED' | 'REJECTED', note: string | null, reviewerUserId: string, scope: Scope): Promise<HouseRelationshipRecord | null>;
  createResidentAtomic(input: { houseId: string; existingPersonId?: string; newPerson?: { name: string; phone?: string | null; gender?: PersonRecord['gender'] }; relationship: { relationshipType: HouseRelationshipRecord['relationshipType']; ownershipShare?: string | null; isPrimaryContact?: boolean; startDate: string; endDate?: string | null }; actorUserId?: string; requestId?: string }, scope: Scope): Promise<{ person: PersonRecord; relationship: HouseRelationshipRecord }>;
}
